import { Alert, Box, Button, FormControl, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material'
import type { GridColDef } from '@mui/x-data-grid'
import dayjs from 'dayjs'
import { useMemo, useState } from 'react'
import { getHttpErrorMessage } from '../../../api/httpError'
import { ConfirmDeleteDialog } from '../../../components/common/ConfirmDeleteDialog'
import { MultiSelectMenuItem } from '../../../components/common/MultiSelectMenuItem'
import { AppIcon } from '../../../components/common/AppIcon'
import { StateChip } from '../../../components/common/StateChip'
import { EntityDrawer } from '../../../components/common/EntityDrawer'
import { PageHeader } from '../../../components/layout/PageHeader'
import { ResourceTable } from '../../../components/tables/ResourceTable'
import { formatDate, formatHours } from '../../../utils/presentation'
import { useCategorias } from '../../categorias/hooks/useCategorias'
import { useEstados } from '../../estados/hooks/useEstados'
import { useSubcategorias } from '../../subcategorias/hooks/useSubcategorias'
import { useUsuarios } from '../../usuarios/hooks/useUsuarios'
import { usePeticiones } from '../hooks/usePeticiones'
import { useHistorialPeticion, usePeticionMutations } from '../hooks/usePeticionMutations'
import type { CambioEstadoRequest, Peticion, PeticionRequest } from '../types/peticion'
import { useCurrentUser } from '../../../app/currentUser'

const id = (v:number|string) => Number(v)
const emptyForm:PeticionRequest={codigo:'',asunto:'',descripcion:'',categoriaId:'',subcategoriaId:'',usuarioId:'',estadoId:'',fechaInicioPrevista:'',fechaFinPrevista:'',fechaInicioReal:'',fechaFinReal:'',horasPrevistas:0,porcentaje:0,rutaDocumentos:'',activo:true}

export function PeticionesPage(){
 const { currentUserId } = useCurrentUser()
 const q=usePeticiones(),eq=useEstados(),cq=useCategorias(),sq=useSubcategorias(),uq=useUsuarios(),m=usePeticionMutations()
 const [selected,setSelected]=useState<Peticion|null>(null),[editOpen,setEditOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[changeOpen,setChangeOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false)
 const [estadosFiltro,setEstadosFiltro]=useState<string[]|null>(null),[categoriasFiltro,setCategoriasFiltro]=useState<string[]>([]),[subcategoriasFiltro,setSubcategoriasFiltro]=useState<string[]>([]),[campoFecha,setCampoFecha]=useState<keyof Peticion>('fechaFinPrevista'),[desde,setDesde]=useState(''),[hasta,setHasta]=useState('')
 const [form,setForm]=useState<PeticionRequest>(emptyForm)
 const [change,setChange]=useState<CambioEstadoRequest>({estadoNuevoId:'',usuarioId:'',fechaCambio:dayjs().format('YYYY-MM-DDTHH:mm'),observaciones:''})
 const history=useHistorialPeticion(selected?.id,historyOpen)
 const estadosSeleccionados=estadosFiltro??(eq.data??[]).filter(e=>!e.estadoFinal).map(e=>String(e.id))
 const subcategoriasDisponibles=useMemo(()=>{const all=sq.data??[];return categoriasFiltro.length?all.filter(s=>categoriasFiltro.includes(String(s.categoriaId))):all},[sq.data,categoriasFiltro])
 const rows=useMemo(()=>(q.data??[]).filter(r=>{if(estadosSeleccionados.length&&!estadosSeleccionados.includes(String(r.estadoId)))return false;if(categoriasFiltro.length&&!categoriasFiltro.includes(String(r.categoriaId)))return false;if(subcategoriasFiltro.length&&!subcategoriasFiltro.includes(String(r.subcategoriaId)))return false;const f=String(r[campoFecha]??'');if(desde&&f&&dayjs(f).isBefore(dayjs(desde),'day'))return false;if(hasta&&f&&dayjs(f).isAfter(dayjs(hasta),'day'))return false;return true}),[q.data,estadosSeleccionados,categoriasFiltro,subcategoriasFiltro,campoFecha,desde,hasta])
 const columns:GridColDef<Peticion>[]=[
  {field:'codigo',headerName:'Código',width:115},{field:'asunto',headerName:'Asunto',flex:1,minWidth:240},
  {field:'estadoNombre',headerName:'Estado',width:145,renderCell:({row})=>{const estado=(eq.data??[]).find(e=>String(e.id)===String(row.estadoId));return <StateChip label={row.estadoNombre} color={estado?.color}/>}},
  {field:'fechaInicioPrevista',headerName:'Inicio prev.',width:115,valueFormatter:v=>formatDate(v)},{field:'fechaFinPrevista',headerName:'Fin prev.',width:115,valueFormatter:v=>formatDate(v)},
  {field:'horasPrevistas',headerName:'H. prev.',width:90,valueFormatter:formatHours},{field:'horasReales',headerName:'H. reales',width:90,valueFormatter:formatHours},{field:'porcentaje',headerName:'%',width:75},
  {field:'acciones',headerName:'Acciones',width:172,sortable:false,renderCell:({row})=><Stack direction="row" spacing={.25}><Tooltip title="Editar petición"><IconButton size="small" color="primary" onClick={()=>openEdit(row)}><AppIcon name="edit" fontSize="small" /></IconButton></Tooltip><Tooltip title="Cambiar estado"><IconButton size="small" color="secondary" onClick={()=>{setSelected(row);setChange({estadoNuevoId:'',usuarioId:currentUserId||row.usuarioId,fechaCambio:dayjs().format('YYYY-MM-DDTHH:mm'),observaciones:''});setChangeOpen(true)}}><AppIcon name="changeState" fontSize="small" /></IconButton></Tooltip><Tooltip title="Ver historial"><IconButton size="small" onClick={()=>{setSelected(row);setHistoryOpen(true)}}><AppIcon name="history" fontSize="small" /></IconButton></Tooltip><Tooltip title="Eliminar petición"><IconButton size="small" color="error" onClick={()=>{setSelected(row);setDeleteOpen(true)}}><AppIcon name="delete" fontSize="small" /></IconButton></Tooltip></Stack>}
 ]
 function openEdit(row?:Peticion){setSelected(row??null);setForm(row?{codigo:row.codigo,asunto:row.asunto,descripcion:row.descripcion??'',categoriaId:row.categoriaId,subcategoriaId:row.subcategoriaId,usuarioId:row.usuarioId,estadoId:row.estadoId,fechaInicioPrevista:row.fechaInicioPrevista??'',fechaFinPrevista:row.fechaFinPrevista??'',fechaInicioReal:row.fechaInicioReal??'',fechaFinReal:row.fechaFinReal??'',horasPrevistas:row.horasPrevistas??0,porcentaje:row.porcentaje??0,rutaDocumentos:row.rutaDocumentos??'',activo:row.activo}:{...emptyForm,usuarioId:currentUserId});setEditOpen(true)}
 async function save(){const payload={...form,categoriaId:id(form.categoriaId),subcategoriaId:id(form.subcategoriaId),usuarioId:id(form.usuarioId),estadoId:id(form.estadoId)};if(selected)await m.updateMutation.mutateAsync({id:selected.id,payload});else await m.createMutation.mutateAsync(payload);setEditOpen(false)}
 async function saveChange(){if(!selected)return;await m.changeMutation.mutateAsync({id:selected.id,payload:{...change,estadoNuevoId:id(change.estadoNuevoId),usuarioId:id(change.usuarioId)}});setChangeOpen(false)}
 const err=m.createMutation.error||m.updateMutation.error||m.deleteMutation.error||m.changeMutation.error
 return <Box><PageHeader title="Peticiones" subtitle="Seguimiento y planificación del trabajo" actionLabel="Nueva petición" actionIcon={<AppIcon name="add" fontSize="small" />} onAction={()=>openEdit()}/>
 {err&&<Alert severity="error" sx={{mb:1}}>{getHttpErrorMessage(err)}</Alert>}
 <Stack direction="row" spacing={1} sx={{mb:1.5}} alignItems="center" flexWrap="wrap" useFlexGap>
 <FormControl size="small" sx={{minWidth:220}}><InputLabel>Estados</InputLabel><Select multiple label="Estados" value={estadosSeleccionados} onChange={e=>setEstadosFiltro(typeof e.target.value==='string'?e.target.value.split(','):e.target.value)}>{(eq.data??[]).map(e=><MultiSelectMenuItem key={e.id} value={String(e.id)} selected={estadosSeleccionados.includes(String(e.id))}>{e.nombre}</MultiSelectMenuItem>)}</Select></FormControl>
 <FormControl size="small" sx={{minWidth:220}}><InputLabel>Categorías</InputLabel><Select multiple label="Categorías" value={categoriasFiltro} onChange={e=>{const values=typeof e.target.value==='string'?e.target.value.split(','):e.target.value;setCategoriasFiltro(values);setSubcategoriasFiltro(prev=>prev.filter(v=>(sq.data??[]).some(s=>String(s.id)===v&&(!values.length||values.includes(String(s.categoriaId))))))}}>{(cq.data??[]).map(c=><MultiSelectMenuItem key={c.id} value={String(c.id)} selected={categoriasFiltro.includes(String(c.id))}>{c.codigo?`${c.codigo} - `:''}{c.nombre}</MultiSelectMenuItem>)}</Select></FormControl>
 <FormControl size="small" sx={{minWidth:220}}><InputLabel>Subcategorías</InputLabel><Select multiple label="Subcategorías" value={subcategoriasFiltro} onChange={e=>setSubcategoriasFiltro(typeof e.target.value==='string'?e.target.value.split(','):e.target.value)}>{subcategoriasDisponibles.map(s=><MultiSelectMenuItem key={s.id} value={String(s.id)} selected={subcategoriasFiltro.includes(String(s.id))}>{s.codigo?`${s.codigo} - `:''}{s.nombre}</MultiSelectMenuItem>)}</Select></FormControl>
 <FormControl size="small" sx={{minWidth:170}}><InputLabel>Fecha a filtrar</InputLabel><Select label="Fecha a filtrar" value={campoFecha} onChange={e=>setCampoFecha(e.target.value as keyof Peticion)}><MenuItem value="fechaAlta">Fecha alta</MenuItem><MenuItem value="fechaInicioPrevista">Inicio previsto</MenuItem><MenuItem value="fechaFinPrevista">Fin previsto</MenuItem><MenuItem value="fechaInicioReal">Inicio real</MenuItem><MenuItem value="fechaFinReal">Fin real</MenuItem></Select></FormControl>
 <TextField size="small" type="date" label="Fecha desde" slotProps={{ inputLabel: { shrink: true } }} value={desde} onChange={e=>setDesde(e.target.value)}/><TextField size="small" type="date" label="Fecha hasta" slotProps={{ inputLabel: { shrink: true } }} value={hasta} onChange={e=>setHasta(e.target.value)}/><Button onClick={()=>{setEstadosFiltro(null);setCategoriasFiltro([]);setSubcategoriasFiltro([]);setDesde('');setHasta('')}}>Limpiar</Button></Stack>
 <ResourceTable rows={rows} columns={columns} loading={q.isLoading} error={q.error} searchFields={['codigo','asunto','descripcion']} searchPlaceholder="Buscar por código, asunto o descripción..."/>
 <EntityDrawer open={editOpen} title={selected?'Editar petición':'Nueva petición'} saving={m.createMutation.isPending||m.updateMutation.isPending} onClose={()=>setEditOpen(false)} onSave={save}><Stack spacing={2}><TextField size="small" label="Código" required value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/><TextField size="small" label="Asunto" required value={form.asunto} onChange={e=>setForm({...form,asunto:e.target.value})}/><TextField size="small" multiline minRows={3} label="Descripción" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/>{[['categoriaId','Categoría',cq.data??[]],['subcategoriaId','Subcategoría',sq.data??[]],['usuarioId','Usuario',uq.data??[]],['estadoId','Estado inicial',eq.data??[]]].map(([k,l,data]:any)=><FormControl key={k} size="small" required><InputLabel>{l}</InputLabel><Select label={l} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{data.map((x:any)=><MenuItem key={x.id} value={String(x.id)}>{x.codigo?`${x.codigo} - `:''}{x.nombre||x.codigo}</MenuItem>)}</Select></FormControl>)}<Stack direction="row" spacing={1}><TextField fullWidth size="small" type="date" label="Inicio previsto" slotProps={{ inputLabel: { shrink: true } }} value={form.fechaInicioPrevista} onChange={e=>setForm({...form,fechaInicioPrevista:e.target.value})}/><TextField fullWidth size="small" type="date" label="Fin previsto" slotProps={{ inputLabel: { shrink: true } }} value={form.fechaFinPrevista} onChange={e=>setForm({...form,fechaFinPrevista:e.target.value})}/></Stack><Stack direction="row" spacing={1}><TextField fullWidth size="small" type="number" label="Horas previstas" value={form.horasPrevistas} onChange={e=>setForm({...form,horasPrevistas:Number(e.target.value)})}/><TextField fullWidth size="small" type="number" label="% avance" value={form.porcentaje} onChange={e=>setForm({...form,porcentaje:Number(e.target.value)})}/></Stack><TextField size="small" label="Ruta documentos" value={form.rutaDocumentos} onChange={e=>setForm({...form,rutaDocumentos:e.target.value})}/></Stack></EntityDrawer>
 <EntityDrawer open={changeOpen} title={`Cambiar estado${selected?` · ${selected.codigo}`:''}`} saving={m.changeMutation.isPending} onClose={()=>setChangeOpen(false)} onSave={saveChange}><Stack spacing={2}><FormControl size="small" required><InputLabel>Nuevo estado</InputLabel><Select label="Nuevo estado" value={change.estadoNuevoId} onChange={e=>setChange({...change,estadoNuevoId:e.target.value})}>{(eq.data??[]).map(e=><MenuItem key={e.id} value={String(e.id)}>{e.nombre}</MenuItem>)}</Select></FormControl><FormControl size="small" required><InputLabel>Usuario</InputLabel><Select label="Usuario" value={change.usuarioId} onChange={e=>setChange({...change,usuarioId:e.target.value})}>{(uq.data??[]).map(u=><MenuItem key={u.id} value={String(u.id)}>{u.nombre}</MenuItem>)}</Select></FormControl><TextField size="small" type="datetime-local" label="Fecha" slotProps={{ inputLabel: { shrink: true } }} value={change.fechaCambio} onChange={e=>setChange({...change,fechaCambio:e.target.value})}/><TextField size="small" multiline minRows={4} required label="Observaciones" value={change.observaciones} onChange={e=>setChange({...change,observaciones:e.target.value})}/></Stack></EntityDrawer>
 <EntityDrawer open={historyOpen} title={`Historial${selected?` · ${selected.codigo}`:''}`} saveLabel="Cerrar" onClose={()=>setHistoryOpen(false)} onSave={()=>setHistoryOpen(false)}>{history.isLoading?<Typography>Cargando…</Typography>:<Stack spacing={1.5}>{(history.data??[]).map(h=><Box key={h.id} sx={{p:1.5,border:'1px solid #e2e8f0',borderRadius:1}}><Typography fontWeight={700} sx={{mb:.75}}>{formatDate(h.fechaCambio,true)}</Typography><Stack direction="row" spacing={1} alignItems="center" sx={{mb:.5}}><StateChip label={h.estadoAnteriorNombre} color={(eq.data??[]).find(e=>String(e.id)===String(h.estadoAnteriorId))?.color}/><AppIcon name="changeState" fontSize="small" color="action"/><StateChip label={h.estadoNuevoNombre} color={(eq.data??[]).find(e=>String(e.id)===String(h.estadoNuevoId))?.color}/></Stack><Typography variant="caption">{h.usuarioNombre||''}</Typography><Typography variant="body2">{h.observaciones||'Sin observaciones'}</Typography></Box>)}</Stack>}</EntityDrawer>
 <ConfirmDeleteDialog open={deleteOpen} text={`¿Está seguro de que desea borrar la petición ${selected?.codigo??''}?`} loading={m.deleteMutation.isPending} onCancel={()=>setDeleteOpen(false)} onConfirm={async()=>{if(selected)await m.deleteMutation.mutateAsync(selected.id);setDeleteOpen(false)}}/>
 </Box>
}
