spring.application.name=tareas-api
spring.datasource.url=jdbc:sqlite:../data/tareas-dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=5000
spring.jpa.database-platform=es.luisev.tareas.config.TareasSQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.port=8081
springdoc.swagger-ui.path=/swagger-ui.html
